#! /bin/sh

INC_DIR=../include
LIB_DIR=../lib
LIB_NAME=oas

if [ -a core* ];
    then
    rm core*
    fi

cat $1 | ../bin/par
# echo "gcc temp.c -I${INC_DIR} -L${LIB_DIR} -l${LIB_NAME} -O2 -g -ggdb -o temp"
# gcc temp.c -I${INC_DIR} -L${LIB_DIR} -l${LIB_NAME} -O2 -g -ggdb -o temp
make -C .. temp DEBUG='-g -ggdb'
