# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap

# Include any dependencies generated for this target.
include src/CMakeFiles/../lib/oas.dir/depend.make

# Include the progress variables for this target.
include src/CMakeFiles/../lib/oas.dir/progress.make

# Include the compile flags for this target's objects.
include src/CMakeFiles/../lib/oas.dir/flags.make

src/CMakeFiles/../lib/oas.dir/project.c.o: src/CMakeFiles/../lib/oas.dir/flags.make
src/CMakeFiles/../lib/oas.dir/project.c.o: src/project.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/../lib/oas.dir/project.c.o"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/../lib/oas.dir/project.c.o   -c /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/project.c

src/CMakeFiles/../lib/oas.dir/project.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../lib/oas.dir/project.c.i"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -E /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/project.c > CMakeFiles/../lib/oas.dir/project.c.i

src/CMakeFiles/../lib/oas.dir/project.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../lib/oas.dir/project.c.s"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -S /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/project.c -o CMakeFiles/../lib/oas.dir/project.c.s

src/CMakeFiles/../lib/oas.dir/project.c.o.requires:
.PHONY : src/CMakeFiles/../lib/oas.dir/project.c.o.requires

src/CMakeFiles/../lib/oas.dir/project.c.o.provides: src/CMakeFiles/../lib/oas.dir/project.c.o.requires
	$(MAKE) -f src/CMakeFiles/../lib/oas.dir/build.make src/CMakeFiles/../lib/oas.dir/project.c.o.provides.build
.PHONY : src/CMakeFiles/../lib/oas.dir/project.c.o.provides

src/CMakeFiles/../lib/oas.dir/project.c.o.provides.build: src/CMakeFiles/../lib/oas.dir/project.c.o

src/CMakeFiles/../lib/oas.dir/record.c.o: src/CMakeFiles/../lib/oas.dir/flags.make
src/CMakeFiles/../lib/oas.dir/record.c.o: src/record.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/../lib/oas.dir/record.c.o"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/../lib/oas.dir/record.c.o   -c /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/record.c

src/CMakeFiles/../lib/oas.dir/record.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../lib/oas.dir/record.c.i"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -E /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/record.c > CMakeFiles/../lib/oas.dir/record.c.i

src/CMakeFiles/../lib/oas.dir/record.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../lib/oas.dir/record.c.s"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -S /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/record.c -o CMakeFiles/../lib/oas.dir/record.c.s

src/CMakeFiles/../lib/oas.dir/record.c.o.requires:
.PHONY : src/CMakeFiles/../lib/oas.dir/record.c.o.requires

src/CMakeFiles/../lib/oas.dir/record.c.o.provides: src/CMakeFiles/../lib/oas.dir/record.c.o.requires
	$(MAKE) -f src/CMakeFiles/../lib/oas.dir/build.make src/CMakeFiles/../lib/oas.dir/record.c.o.provides.build
.PHONY : src/CMakeFiles/../lib/oas.dir/record.c.o.provides

src/CMakeFiles/../lib/oas.dir/record.c.o.provides.build: src/CMakeFiles/../lib/oas.dir/record.c.o

src/CMakeFiles/../lib/oas.dir/scan.c.o: src/CMakeFiles/../lib/oas.dir/flags.make
src/CMakeFiles/../lib/oas.dir/scan.c.o: src/scan.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/CMakeFiles $(CMAKE_PROGRESS_3)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/../lib/oas.dir/scan.c.o"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/../lib/oas.dir/scan.c.o   -c /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/scan.c

src/CMakeFiles/../lib/oas.dir/scan.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../lib/oas.dir/scan.c.i"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -E /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/scan.c > CMakeFiles/../lib/oas.dir/scan.c.i

src/CMakeFiles/../lib/oas.dir/scan.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../lib/oas.dir/scan.c.s"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -S /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/scan.c -o CMakeFiles/../lib/oas.dir/scan.c.s

src/CMakeFiles/../lib/oas.dir/scan.c.o.requires:
.PHONY : src/CMakeFiles/../lib/oas.dir/scan.c.o.requires

src/CMakeFiles/../lib/oas.dir/scan.c.o.provides: src/CMakeFiles/../lib/oas.dir/scan.c.o.requires
	$(MAKE) -f src/CMakeFiles/../lib/oas.dir/build.make src/CMakeFiles/../lib/oas.dir/scan.c.o.provides.build
.PHONY : src/CMakeFiles/../lib/oas.dir/scan.c.o.provides

src/CMakeFiles/../lib/oas.dir/scan.c.o.provides.build: src/CMakeFiles/../lib/oas.dir/scan.c.o

src/CMakeFiles/../lib/oas.dir/select.c.o: src/CMakeFiles/../lib/oas.dir/flags.make
src/CMakeFiles/../lib/oas.dir/select.c.o: src/select.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/CMakeFiles $(CMAKE_PROGRESS_4)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/../lib/oas.dir/select.c.o"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/../lib/oas.dir/select.c.o   -c /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/select.c

src/CMakeFiles/../lib/oas.dir/select.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../lib/oas.dir/select.c.i"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -E /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/select.c > CMakeFiles/../lib/oas.dir/select.c.i

src/CMakeFiles/../lib/oas.dir/select.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../lib/oas.dir/select.c.s"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -S /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/select.c -o CMakeFiles/../lib/oas.dir/select.c.s

src/CMakeFiles/../lib/oas.dir/select.c.o.requires:
.PHONY : src/CMakeFiles/../lib/oas.dir/select.c.o.requires

src/CMakeFiles/../lib/oas.dir/select.c.o.provides: src/CMakeFiles/../lib/oas.dir/select.c.o.requires
	$(MAKE) -f src/CMakeFiles/../lib/oas.dir/build.make src/CMakeFiles/../lib/oas.dir/select.c.o.provides.build
.PHONY : src/CMakeFiles/../lib/oas.dir/select.c.o.provides

src/CMakeFiles/../lib/oas.dir/select.c.o.provides.build: src/CMakeFiles/../lib/oas.dir/select.c.o

src/CMakeFiles/../lib/oas.dir/sort.c.o: src/CMakeFiles/../lib/oas.dir/flags.make
src/CMakeFiles/../lib/oas.dir/sort.c.o: src/sort.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/CMakeFiles $(CMAKE_PROGRESS_5)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/../lib/oas.dir/sort.c.o"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/../lib/oas.dir/sort.c.o   -c /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/sort.c

src/CMakeFiles/../lib/oas.dir/sort.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../lib/oas.dir/sort.c.i"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -E /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/sort.c > CMakeFiles/../lib/oas.dir/sort.c.i

src/CMakeFiles/../lib/oas.dir/sort.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../lib/oas.dir/sort.c.s"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && /usr/bin/gcc  $(C_DEFINES) $(C_FLAGS) -S /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/sort.c -o CMakeFiles/../lib/oas.dir/sort.c.s

src/CMakeFiles/../lib/oas.dir/sort.c.o.requires:
.PHONY : src/CMakeFiles/../lib/oas.dir/sort.c.o.requires

src/CMakeFiles/../lib/oas.dir/sort.c.o.provides: src/CMakeFiles/../lib/oas.dir/sort.c.o.requires
	$(MAKE) -f src/CMakeFiles/../lib/oas.dir/build.make src/CMakeFiles/../lib/oas.dir/sort.c.o.provides.build
.PHONY : src/CMakeFiles/../lib/oas.dir/sort.c.o.provides

src/CMakeFiles/../lib/oas.dir/sort.c.o.provides.build: src/CMakeFiles/../lib/oas.dir/sort.c.o

# Object files for target ../lib/oas
__/lib/oas_OBJECTS = \
"CMakeFiles/../lib/oas.dir/project.c.o" \
"CMakeFiles/../lib/oas.dir/record.c.o" \
"CMakeFiles/../lib/oas.dir/scan.c.o" \
"CMakeFiles/../lib/oas.dir/select.c.o" \
"CMakeFiles/../lib/oas.dir/sort.c.o"

# External object files for target ../lib/oas
__/lib/oas_EXTERNAL_OBJECTS =

src/lib../lib/oas.a: src/CMakeFiles/../lib/oas.dir/project.c.o
src/lib../lib/oas.a: src/CMakeFiles/../lib/oas.dir/record.c.o
src/lib../lib/oas.a: src/CMakeFiles/../lib/oas.dir/scan.c.o
src/lib../lib/oas.a: src/CMakeFiles/../lib/oas.dir/select.c.o
src/lib../lib/oas.a: src/CMakeFiles/../lib/oas.dir/sort.c.o
src/lib../lib/oas.a: src/CMakeFiles/../lib/oas.dir/build.make
src/lib../lib/oas.a: src/CMakeFiles/../lib/oas.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking C static library lib../lib/oas.a"
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && $(CMAKE_COMMAND) -P CMakeFiles/../lib/oas.dir/cmake_clean_target.cmake
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../lib/oas.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/CMakeFiles/../lib/oas.dir/build: src/lib../lib/oas.a
.PHONY : src/CMakeFiles/../lib/oas.dir/build

src/CMakeFiles/../lib/oas.dir/requires: src/CMakeFiles/../lib/oas.dir/project.c.o.requires
src/CMakeFiles/../lib/oas.dir/requires: src/CMakeFiles/../lib/oas.dir/record.c.o.requires
src/CMakeFiles/../lib/oas.dir/requires: src/CMakeFiles/../lib/oas.dir/scan.c.o.requires
src/CMakeFiles/../lib/oas.dir/requires: src/CMakeFiles/../lib/oas.dir/select.c.o.requires
src/CMakeFiles/../lib/oas.dir/requires: src/CMakeFiles/../lib/oas.dir/sort.c.o.requires
.PHONY : src/CMakeFiles/../lib/oas.dir/requires

src/CMakeFiles/../lib/oas.dir/clean:
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src && $(CMAKE_COMMAND) -P CMakeFiles/../lib/oas.dir/cmake_clean.cmake
.PHONY : src/CMakeFiles/../lib/oas.dir/clean

src/CMakeFiles/../lib/oas.dir/depend:
	cd /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src /Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/lib/oas.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/CMakeFiles/../lib/oas.dir/depend

