# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

src/lib/oas.dir/project.c.o: src/project.c
src/lib/oas.dir/project.c.o: src/../include/project.h
src/lib/oas.dir/project.c.o: src/../include/record.h

src/lib/oas.dir/record.c.o: src/record.c
src/lib/oas.dir/record.c.o: src/../include/record.h

src/lib/oas.dir/scan.c.o: src/scan.c
src/lib/oas.dir/scan.c.o: src/../include/record.h
src/lib/oas.dir/scan.c.o: src/../include/scan.h

src/lib/oas.dir/select.c.o: src/select.c
src/lib/oas.dir/select.c.o: src/../include/record.h
src/lib/oas.dir/select.c.o: src/../include/select.h

src/lib/oas.dir/sort.c.o: src/sort.c
src/lib/oas.dir/sort.c.o: src/../include/record.h
src/lib/oas.dir/sort.c.o: src/../include/sort.h

