# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile C with /usr/bin/gcc
C_FLAGS = -I/Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap -I/Users/lalanne/MyCode/GitHubProjects/oas/goas/oas_mmap/src/../include   

C_DEFINES = 

